# Generated by Django 3.2.3 on 2021-05-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120, verbose_name='Title')),
                ('image', models.ImageField(blank=True, default='', upload_to='media/img/blog/', verbose_name='Image 2x1')),
                ('content', models.TextField(verbose_name='Content')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='media/img/coaches/', verbose_name='Photo 1x1')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Name')),
                ('last_name', models.CharField(default='', max_length=30, verbose_name='Last name')),
                ('occupation', models.CharField(default='', max_length=50, verbose_name='Occupation')),
                ('achievements', models.CharField(default='', max_length=225, verbose_name='Achieves')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='media/img/clubGallery/', verbose_name='Photo 640x500')),
                ('description', models.CharField(blank=True, default='', max_length=70, verbose_name='Short description')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(default='', upload_to='media/video/clubGallery', verbose_name='Video')),
                ('description', models.CharField(default='', max_length=70, verbose_name='Short description')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
        migrations.CreateModel(
            name='MainSlides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='Title')),
                ('description', models.CharField(default='', max_length=50, verbose_name='Short description')),
                ('image', models.ImageField(default='', upload_to='media/img/slides/', verbose_name='Slide image')),
            ],
        ),
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70, verbose_name='Title')),
                ('image', models.ImageField(default='', upload_to='media/img/news/', verbose_name='Image 1x1')),
                ('content', models.TextField(verbose_name='Content')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Partner name')),
                ('image', models.ImageField(default='', upload_to='media/img/partners/', verbose_name='Logo')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Name')),
                ('last_name', models.CharField(default='', max_length=30, verbose_name='Last name')),
                ('rank', models.CharField(default='', max_length=50, verbose_name='Rank')),
            ],
        ),
    ]
