# Generated by Django 3.2.3 on 2021-05-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210523_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['date', 'is_active'], 'verbose_name': 'blog', 'verbose_name_plural': 'blogs'},
        ),
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['name', 'is_active'], 'verbose_name': 'coach', 'verbose_name_plural': 'coaches'},
        ),
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'ordering': ['date', 'is_active'], 'verbose_name': 'photo', 'verbose_name_plural': 'gallery photos'},
        ),
        migrations.AlterModelOptions(
            name='galleryvideo',
            options={'ordering': ['date', 'is_active'], 'verbose_name': 'video', 'verbose_name_plural': 'gallery videos'},
        ),
        migrations.AlterModelOptions(
            name='mainslides',
            options={'ordering': ['title', 'is_active'], 'verbose_name': 'main menu slides', 'verbose_name_plural': 'slide'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['date', 'is_active'], 'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'ordering': ['name', 'is_active'], 'verbose_name': 'partner', 'verbose_name_plural': 'partners'},
        ),
        migrations.AlterModelOptions(
            name='teammembers',
            options={'ordering': ['name', 'is_active'], 'verbose_name': 'team members', 'verbose_name_plural': 'member'},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='date_time',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='date_time',
            new_name='date',
        ),
    ]
