# Generated by Django 3.2.3 on 2021-05-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210523_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainslides',
            options={'ordering': ['title', 'is_active'], 'verbose_name': 'slide', 'verbose_name_plural': 'main menu slides'},
        ),
        migrations.AlterModelOptions(
            name='teammembers',
            options={'ordering': ['name', 'is_active'], 'verbose_name': 'member', 'verbose_name_plural': 'team members'},
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='', upload_to='img/news/', verbose_name='Image 1x1'),
        ),
    ]
