# Generated by Django 3.2.3 on 2021-05-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210524_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_content',
            field=models.TextField(default='', verbose_name='Short_description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(default='', verbose_name='Content'),
        ),
    ]
