# Generated by Django 3.2.3 on 2021-05-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210525_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='short_content',
        ),
        migrations.AddField(
            model_name='news',
            name='short_description',
            field=models.TextField(blank=True, default='', max_length=70, verbose_name='Short_description'),
        ),
    ]
