# Generated by Django 3.2.3 on 2021-05-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210525_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='short_description',
        ),
    ]
