# Generated by Django 3.2.3 on 2021-05-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_news_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryphoto',
            name='description',
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='title',
            field=models.CharField(blank=True, default='', max_length=70, verbose_name='Title'),
        ),
    ]
