# Generated by Django 3.2.3 on 2021-05-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_teammembers_biography'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40, verbose_name='Name')),
                ('last_name', models.CharField(default='', max_length=40, verbose_name='Last_name')),
                ('occupation', models.CharField(default='', max_length=50, verbose_name='Occupation')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'team members',
                'ordering': ['name', 'last_name'],
            },
        ),
    ]
