# Generated by Django 3.2.3 on 2021-05-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_partners_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='history',
            field=models.TextField(default='', verbose_name='History'),
        ),
    ]
