# Generated by Django 3.2.3 on 2021-05-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_partner_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainSlides',
            new_name='MainSlide',
        ),
    ]
