# Generated by Django 3.2.3 on 2021-05-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_mainslides_mainslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Creation date'),
        ),
    ]
