# Generated by Django 3.2.3 on 2021-05-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='', max_length=20, verbose_name='Created by'),
        ),
    ]
