# Generated by Django 3.2.3 on 2021-05-29 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_blog_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['is_active'], 'verbose_name': 'blog', 'verbose_name_plural': 'blogs'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
    ]
