# Generated by Django 3.2.3 on 2021-05-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210530_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='image',
            field=models.ImageField(default='', upload_to="img/team's members/", verbose_name='Photo'),
        ),
    ]
