# Generated by Django 3.2.4 on 2021-06-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_teammembers_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(default='', max_length=60, verbose_name='Last name')),
                ('email', models.CharField(default='', max_length=100, verbose_name='E-mail')),
                ('message', models.TextField(default='', verbose_name='Message')),
                ('send_data', models.DateField(verbose_name='Data')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'ordering': ['-send_data'],
            },
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='image',
            field=models.ImageField(default='', upload_to='img/team members/', verbose_name='Photo'),
        ),
    ]
