# Generated by Django 3.2.4 on 2021-06-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210613_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='send_data',
            field=models.DateField(editable=False, verbose_name='Data'),
        ),
    ]
