# Generated by Django 3.2.4 on 2021-06-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_contact_send_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='send_data',
            field=models.DateField(auto_now_add=True, verbose_name='Data'),
        ),
    ]
